# Application specific
app_name: "Go Rest Boilerplate"
app_env: "development"
app_host: "localhost"
app_port: 4000

# Oauth2 specific
github_client_id:
github_client_secret: 
github_callback_url: 

# Session specific
session_secret: 
session_name: "session"

# Database specific
postgres_user: "postgres"
postgres_password: 
postgres_host: "localhost"
postgres_port: 5432
postgres_db: "goboilerplate"
postgres_ssl_mode: "prefer"

